### ISSUE TITLE
Export to something confluence friendly. 

### ISSUE THREAD

**Issue by jaymichls** [tweeres04/better-retros#5]

**Comment by jaymichls** [comment]
Does confluence have an api we could use alternatively

**Comment by davidgraig** [comment]
I would also accept markdown?  https://community.atlassian.com/t5/Confluence-questions/Import-markdown-into-Confluence/qaq-p/211797 seems to say that we _can_ make it work.

**Comment by tweeres04** [comment]
Done in #15
