### ISSUE TITLE
Move text inputs to top of columns

### ISSUE THREAD

**Issue by nanstey** [tweeres04/better-retros#7]
When the text inputs are at the bottom of the columns they will become obscured and misaligned as cards are added. If they are at the top of the column they will maintain their position.

**Comment by tweeres04** [comment]
Done in https://github.com/tweeres04/better-retros/commit/e9d7adff52c5e903cb5f306a1d03b093ed3354ea

**Comment by tweeres04** [comment]
Done in https://github.com/tweeres04/better-retros/commit/e9d7adff52c5e903cb5f306a1d03b093ed3354ea
